[package]
name = "libcontainer"
version = "0.0.2"
authors = ["youki team"]
edition = "2021"
rust-version = "1.58.1"
description = "Library for container creation"

[dependencies]
anyhow = "1.0"
caps = "0.5.3"

chrono = { version="0.4", features = ["serde"] }
crossbeam-channel = "0.5"
dbus = "0.9.5"
fastrand = "1.6.0"
futures = { version = "0.3", features = ["thread-pool"] }
libc = "0.2.117"
log = "0.4"
mio = { version = "0.8.0", features = ["os-ext", "os-poll"] }
nix = "0.23.1"
oci-spec = "0.5.3"
path-clean = "0.1.0"
procfs = "0.12.0"
prctl = "1.0.0"
libcgroups = { version = "0.0.2", path = "../libcgroups" }
libseccomp = { version = "0.0.2", path = "../libseccomp" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
oci-spec = { version = "0.5.3", features = ["proptests"] }
quickcheck = "1"
serial_test = "0.5.1"
